### ISSUE TITLE
Switch semantically should be an input[type='checkbox'] - not div

### ISSUE THREAD

**Issue by pawel763** [sl-design-system/components#1268] opened 2024-05-23 08:49 UTC
### Provide a general summary of the issue here

Semantically switch is kind of checkbox with 2 values possible.
Inputs are important in frameworks, e.g. in Angular they are useful with [Reactive Forms](https://v17.angular.io/guide/reactive-forms) and directive [`FormControl`](https://v17.angular.io/api/forms/FormControlDirective)

### 🕵️‍♀️ Where does this bug appear?

- [ ] Storybook
- [ ] Figma Toolkit
- [ ] My own environment

### 🤔 Expected Behavior?

![image](https://github.com/sl-design-system/components/assets/161736163/3a53de7f-d88a-4245-ac08-64cc5b8b4d07)

### 😯 Current Behavior

![image](https://github.com/sl-design-system/components/assets/161736163/307f0a04-d2c2-4034-a9b6-035e69d680b1)

### 🖥️ Steps to Reproduce

3. Scroll to '....'
4. Check console
5. See error

### 🎨 Your Theme(s)

Bingel INT

**Comment by jpzwarte** [comment] 2024-05-23 10:46
@pawel763 The switch component uses `ElementInternals` instead of having an `<input>` element in the light DOM. Also there is a proposal underway for `<input type="switch">` :)

**Comment by DanielleRameau** [comment] 2024-06-06 08:08
@pawel763 it is unclear to us what the issue is right now. The implementation is by design, could you give more context?

**Comment by jpzwarte** [comment] 2024-06-06 08:32
Closing after discussing it with Pawel in Slack.

**Closed by jpzwarte** 2024-06-06 08:32 UTC
Labels: bug, development, triage
