### ISSUE TITLE
[GRID] Make it possible to ellipsize long fields  and add a hover tooltip

### ISSUE THREAD

**Issue by PaulineKK** [sl-design-system/components#1453] opened 2024-08-15 07:10 UTC
### Provide a general summary of the feature here

We would like it to be possible to ellipsize long fields, and display a hover tooltip with the content. The tooltip should only be shown when the content is ellipsized.

### 🤔 Expected Behavior?

Ellipsize content when that's preferred

### 😯 Current Behavior

You cannot ellipsize content. When the content is too long, the content will break into multiple lines.

### 🔦 Context

Sometimes the content of a column is not important enough to have the need to be fully shown.

### 🧢 Your Product/Team

Magister

**Comment by jpzwarte** [comment] 2024-08-15 07:28
This looks like a duplicate of https://github.com/sl-design-system/components/issues/1436 ?

**Comment by PaulineKK** [comment] 2024-08-15 09:06
Duplicate

**Closed** 2024-08-15 09:06 UTC
Labels: enhancement, development, triage
